Module1 task3
htmlacademy-ecmascript/1757859-cinemaddict-15 pull request #3
Opened 2021-07-27 20:53 UTC by RanelGM

2021-07-27 22:37 UTC, andreevsm requested changes

2021-07-27 22:37 UTC, andreevsm commented on src/main.js
> +render(siteHeaderElement, createProfileHeaderTemplate(), 'beforeend');
Очень часто повторяется передача параметра `beforeend`
Предлагаю сделать его по умолчанию:
```
const render = (container, template, position = `beforeend`) => {
```
И тогда можно будет сделать
```
render(siteHeaderElement, createProfileHeaderTemplate());
```

2021-07-28 20:38 UTC, andreevsm requested changes

2021-07-28 20:38 UTC, andreevsm commented on src/main.js
> +import { createMenuNavigation } from './view/menu-navigation';
Давай будем именовать функции в одном стиле. У тебя есть отличный пример `createProfileHeaderTemplate`, то есть функция, которая создает темплейт шапки профиля. Давай остальным также добавим в конце `Template`

2021-07-28 20:50 UTC, RanelGM commented on src/main.js
> +import { createMenuNavigation } from './view/menu-navigation';
Спасибо, исправил

2021-07-29 06:37 UTC, merged